server:
  port: 8080
host:
  images: http://loclahost:3000/uploads/images/
jwt:
  secret: dsfsdfdsfsdf
spring:
  mail:
    password: rkruzyzziwprwcho
    host: smtp.gmail.com
    port: 587
    username: restaurantix20@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomerse
    username: postgres
    password:
logging:
  level:
    org:
      hibernate:
        sql: info
        type: info


