jwt:
  secret: ${TOKEN_SECRET}
spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USES}
    password: ${DB_PASSWORD}

